### PR TITLE
Use find instead of filter to find first dist file which matches file…

### PR DESCRIPTION
**Pull request by zzarcon**
## What Changed & Why

Changed **filter** method by **find** method for retrieve the first file which matches the **filePattern**. This way we save time since we return as soon as we find an occurrence and space since we don't want to have an array just to pick always the first value. 

IMO, also I think looks more readable now. Thanks!

### CODE REVIEW

**Comment by lukemelia** [comment]
Thanks @zzarcon. Can you look into the failing tests? Not sure off the top of my head why your change would have caused anything to fail, but it seems to have.

**Comment by zzarcon** [comment]
@lukemelia maybe it's because the Node version of Travis **v0.12.14** and the **find** method is not supported? 

Works fine for me locally 



There's any reason of why want to support that node version? Thanks!

**Comment by achambers** [comment]
Isn't `Array.prototype.find` an ES2015 function? We don't transpire the
ember-cli-deploy code as yet so would this actually work?

**Comment by ghedamat** [comment]
@zzarcon I'm afraid we need to support as ember-cli is still supporting node `0.10.X` and up

let me know if you have time to tackle this,
I'd love to get it in

**Comment by zzarcon** [comment]
@achambers unfortunately **find** is not supported on **0.12.14**: 



@ghedamat I think you are right, we must be aligned with the [ember-cli node version](https://github.com/ember-cli/ember-cli/blob/master/package.json#L26) :(

Just for my info, do you know why ember-cli is still supporting that version?

Thanks!

**Comment by ghedamat** [comment]
@zzarcon I'm honestly not entirely sure. You're probably better off asking on slack about this.

I guess we'll close this pr for now and maybe revisit later when ember cli updates 

Thanks anyway!

**Pull request closed without merging**
