### PR TITLE
Change git-tag-commit data generator to use most recent ancestor tag

### LINKED ISSUE #27: README says git-tag-commit uses most recent tag, but it doesn't work unless current commit has a tag

### LINKED ISSUE #50: Add latestAnnotatedTag support for git-tag-commit
Addresses part of https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/issues/27

Depends on https://github.com/rwjblue/git-repo-info/issues/33

### PR DESCRIPTION
**Pull request by courajs**
## What Changed & Why
Upgraded `git-repo-info` in order to take advantage of the `lastTag` feature. This allows deploying releases using the git-tag-commit generator without creating new a git tag. This is useful for pushing to staging before graduating a release to a full version bump.

## Related issues
`lastTag` added to git-repo-info in https://github.com/rwjblue/git-repo-info/pull/37, released in v2.0.0
Closes #27 
Closes #28 
Closes #50 

## PR Checklist
- [x] Add tests
- [x] Add documentation (this was the behavior implied by the current documentation)

## People
@reidab, @lukemelia, @jrowlingson,

### CODE REVIEW

**Comment by courajs** [comment]
Ping @lukemelia @achambers if you have a chance to look at this

**Comment by jrowlingson** [comment]
> This allows deploying releases using the git-tag-commit generator without creating new a git tag. 

@courajs Could you expand a bit on this? I am interested in your deployment workflow.

**Comment by courajs** [comment]
Without this, `ember deploy` fails if the current commit isn't tagged. With it, as long as an ancestor commit is tagged, it will simply append the commit sha to the most recent tag name, and allow the deploy:
```
-   timestamp           | revision
- =================================
- > 2018/03/30 19:16:11 | v0.1.0+a96d264a
-   2018/03/30 19:03:41 | v0.1.0+e3f28123
-   2018/03/30 15:32:09 | v0.1.0+e6d393e4
-   2018/03/30 15:30:14 | v0.1.0+3a75100f
-   2018/03/30 13:41:23 | v0.1.0+7b5e9631
```
While you might not do this for production, it's useful when your versioning process involves validation in staging before approving a version bump.

**Comment by lukemelia** [comment]
Thanks @courajs. I'm +1 on this. @achambers we should make sure that the git revision data plugin gets a similar bump.

**Comment by achambers** [comment]
@lukemelia said:

> Thanks @courajs. I'm +1 on this. @achambers we should make sure that the git revision data plugin gets a similar bump.

Roger that.

**Comment by ludalex** [comment]
Any plans on merging this?

**Comment by demee** [comment]
LGTM!

**Comment by lukemelia** [comment]
I know it's been a while. My apologies. @courajs: if you (or anyone else) wants to take initiative to review this and resolve the conflicts, I'll get it merged.

**Comment by courajs** [comment]
@lukemelia Conflicts are resolved! Tests are passing and it looks like not too much else has changed in the add-on, so I think this is probably still a good patch?

**Pull request merged**
